"""Add StudentProfile model

Revision ID: 50847becc9bc
Revises: 54e7de456d75
Create Date: 2026-06-10 23:06:18.246442

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50847becc9bc'
down_revision = '54e7de456d75'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('dob', sa.Date(), nullable=False),
    sa.Column('mobile', sa.String(length=20), nullable=False),
    sa.Column('father_name', sa.String(length=120), nullable=True),
    sa.Column('mother_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_name', sa.String(length=120), nullable=True),
    sa.Column('guardian_mobile', sa.String(length=20), nullable=True),
    sa.Column('college', sa.String(length=120), nullable=True),
    sa.Column('university', sa.String(length=120), nullable=True),
    sa.Column('course', sa.String(length=120), nullable=True),
    sa.Column('semester', sa.String(length=20), nullable=True),
    sa.Column('admission_year', sa.Integer(), nullable=True),
    sa.Column('completion_year', sa.Integer(), nullable=True),
    sa.Column('hod_name', sa.String(length=120), nullable=True),
    sa.Column('hod_phone', sa.String(length=20), nullable=True),
    sa.Column('diet', sa.Enum('veg', 'non-veg', name='diet_enum'), nullable=True),
    sa.Column('food_items', sa.JSON(), nullable=True),
    sa.Column('aadhaar_path', sa.String(length=200), nullable=True),
    sa.Column('ration_card_path', sa.String(length=200), nullable=True),
    sa.Column('college_id_path', sa.String(length=200), nullable=True),
    sa.Column('agreed', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_profile')
    # ### end Alembic commands ###
