"""add fields to leave request

Revision ID: 68c7477a47e0
Revises: ff2a6d3c5cd0
Create Date: 2026-06-29 22:17:00.836083

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68c7477a47e0'
down_revision = 'ff2a6d3c5cd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('shift_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('expected_return_time', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('attachment_path', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ocr_text', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ocr_extracted_dates', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('ocr_days', sa.Integer(), nullable=True))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###


    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('ocr_days')
        batch_op.drop_column('ocr_extracted_dates')
        batch_op.drop_column('ocr_text')
        batch_op.drop_column('attachment_path')
        batch_op.drop_column('expected_return_time')
        batch_op.drop_column('shift_type')

    # ### end Alembic commands ###
