"""add status column

Revision ID: 6c76dc4cb974
Revises: 50847becc9bc
Create Date: 2026-06-11 20:23:49.775516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c76dc4cb974'
down_revision = '50847becc9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('status')

    # ### end Alembic commands ###
