"""Add extracted_cgpa to MarksCard

Revision ID: 798cd1059f24
Revises: 82f03f842c0e
Create Date: 2026-06-16 23:50:14.269750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798cd1059f24'
down_revision = '82f03f842c0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks_cards', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extracted_cgpa', sa.String(length=10), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('marks_cards', schema=None) as batch_op:
        batch_op.drop_column('extracted_cgpa')

    # ### end Alembic commands ###
