"""Add docs to staff profile

Revision ID: 82f03f842c0e
Revises: ee38ffc890ab
Create Date: 2026-06-16 21:24:15.986500

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82f03f842c0e'
down_revision = 'ee38ffc890ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.drop_column('extended_to_date')
        batch_op.drop_column('extension_status')

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aadhaar_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('ration_card_path', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('aadhaar_verified', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ration_verified', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.drop_column('ration_verified')
        batch_op.drop_column('aadhaar_verified')
        batch_op.drop_column('ration_card_path')
        batch_op.drop_column('aadhaar_path')

    with op.batch_alter_table('leave_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extension_status', sa.VARCHAR(length=20), server_default=sa.text("'None'"), nullable=True))
        batch_op.add_column(sa.Column('extended_to_date', sa.DATE(), nullable=True))

    # ### end Alembic commands ###
