"""Rename completion_year to course_duration

Revision ID: bab65a71f305
Revises: eb98ed10ed03
Create Date: 2026-06-18 14:07:11.408891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab65a71f305'
down_revision = 'eb98ed10ed03'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_duration', sa.Integer(), nullable=True))
        batch_op.drop_column('completion_year')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_year', sa.INTEGER(), nullable=True))
        batch_op.drop_column('course_duration')

    # ### end Alembic commands ###
