"""add food_menu model

Revision ID: dbd1695bf5fb
Revises: 6c76dc4cb974
Create Date: 2026-06-11 20:45:53.267370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbd1695bf5fb'
down_revision = '6c76dc4cb974'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('food_menu',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day', sa.String(length=20), nullable=False),
    sa.Column('breakfast', sa.String(length=200), nullable=True),
    sa.Column('lunch', sa.String(length=200), nullable=True),
    sa.Column('snacks', sa.String(length=200), nullable=True),
    sa.Column('dinner', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('food_menu')
    # ### end Alembic commands ###
