"""add emergency_contact to student_profile

Revision ID: eb98ed10ed03
Revises: 798cd1059f24
Create Date: 2026-06-18 13:19:43.422952

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb98ed10ed03'
down_revision = '798cd1059f24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emergency_contact', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('emergency_contact')

    # ### end Alembic commands ###
