"""Added aadhaar and ration card numbers

Revision ID: ee38ffc890ab
Revises: dbd1695bf5fb
Create Date: 2026-06-16 13:14:45.431346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ee38ffc890ab'
down_revision = 'dbd1695bf5fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('address', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('marital_status', sa.String(length=50), nullable=True))

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('aadhaar_number', sa.String(length=12), nullable=True))
        batch_op.add_column(sa.Column('ration_card_number', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('ration_card_number')
        batch_op.drop_column('aadhaar_number')

    with op.batch_alter_table('staff_profiles', schema=None) as batch_op:
        batch_op.drop_column('marital_status')
        batch_op.drop_column('address')
        batch_op.drop_column('email')

    # ### end Alembic commands ###
