"""Add completion_year back to student_profile

Revision ID: ff2a6d3c5cd0
Revises: bab65a71f305
Create Date: 2026-06-18 14:16:18.352777

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff2a6d3c5cd0'
down_revision = 'bab65a71f305'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_year', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_column('completion_year')

    # ### end Alembic commands ###
